### PR TITLE
Add redfish support for SBE dumps

### PR DESCRIPTION
**Pull request by asmithakarun**
Tested By:

Listing of an SBE dump:
** curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Entries/SBE_7
{
"@odata.id": "/redfish/v1/Systems/system/LogServices/Dump/Entries/SBE_7",
"@odata.type": "#LogEntry.v1_7_0.LogEntry",
"AdditionalDataSizeBytes": 283079,
"AdditionalDataURI": "/redfish/v1/Systems/system/LogServices/Dump/Entries/SBE_7/attachment",
"Created": "2021-10-05T03:43:59+00:00",
"DiagnosticDataType": "OEM",
"EntryType": "Event",
"Id": "SBE_7",
"Name": "System Dump Entry",
"OEMDiagnosticDataType": "SBE"
}

Deletion of an SBE dump:
** curl -k -H "X-Auth-Token: $bmc_token" -X DELETE https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Entries/SBE_5

Clear all host dumps:
** curl -k -H "X-Auth-Token: $bmc_token" -X POST https://${bmc}/redfish/v1/Managers/bmc/LogServices/Dump/Actions/LogService.ClearLog

The upstream for this is at:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/46823/

### CODE REVIEW

**Comment by gtmills** [comment]
@asmithakarun Can we address merge conflicts, get some reviews upstream?

**Review by sunharis — APPROVED** [review]
Looks good to me. This can go in independently without the backend changes.

**Comment by asmithakarun** [comment]
> @asmithakarun Can we address merge conflicts, get some reviews upstream?
Sure will resolve the merge conflict
But still I am waiting for the reviews for the previous commits in the commit chain.

**Comment by gtmills** [comment]
> But still I am waiting for the reviews for the previous commits in the commit chain.

Can a person or 2 on the squad take a look?

**Pull request merged**
