### PR TITLE
1050: Security fixes.

### PR DESCRIPTION
**Pull request by ojayanth**
PR Includes below fixes:

1. Security: Deleted users can continue to use their Redfish session: 
    https://gerrit.openbmc.org/c/openbmc/bmcweb/+/55050
2. PenTesting:Security- found couple of low severity missing header vulnerabilities on BMC
    -  https://gerrit.openbmc.org/c/openbmc/bmcweb/+/63455
    -  https://gerrit.openbmc.org/c/openbmc/bmcweb/+/64205

### CODE REVIEW

**Comment by ojayanth** [comment]
Verified Status:
Fix 1 verified.
Fix 2 : Provided patch to @prkatti1 for pen testing.

**Comment by gtmills** [comment]
@ojayanth Did you just cherrypick these from upstream? Or is there any additional code here ?

**Comment by gtmills** [comment]
@ojayanth #2 doesn't break anything like the GUI right? Can you do a sanity check?

**Comment by ojayanth** [comment]
> @ojayanth #2 doesn't break anything like the GUI right? Can you do a sanity check?

@prkatti1 agreed to help to verify this.

**Comment by ojayanth** [comment]
> @ojayanth Did you just cherrypick these from upstream? Or is there any additional code here ?

Cherry pick only minor change i made "#include <algorithm>"  instead of "#include "algorithm"  in include/sessions.hpp

**Comment by ojayanth** [comment]
> > @ojayanth #2 doesn't break anything like the GUI right? Can you do a sanity check?
> 
> @prkatti1 agreed to help to verify this.

@prkatti1 verified the patch.

**Review by gtmills — APPROVED** [review]

**Pull request merged**
