### PR TITLE
Add concurrent KVM sessions support

### PR DESCRIPTION
**Pull request by LuluTHSu**
Currently, bmcweb allows just one KVM session. To make it support
multiple concurrent KVM sessions, this commit adds KVM session class
implementation. It limits the number of sessions to 4 to secure the
connection quality.

Tested: Up to 4 concurrent KVM sessions worked.

Change-Id: I37342ba2e30f840131d6287b4249a298aa17a1f1
Signed-off-by: Jae Hyun Yoo <jae.hyun.yoo@linux.intel.com>
Signed-off-by: LuluTHSu <Lulu_Su@wistron.com>

### CODE REVIEW

**Review by geissonator — COMMENTED** [review]
My main concern here is risk. OP940 is based on some old code and it's really just been a fix release. Do we see this as introducing a lot of risk or is it overall a pretty safe patch to bring back?

**Comment by gtmills** [comment]
> My main concern here is risk. OP940 is based on some old code and it's really just been a fix release. 

+1. Can you explain more why we need this.

**Comment by Erich-Hauptli** [comment]
It was decided that P9 HMC would be build on OP940.  The P9 HMC uses KVM much more heavily than any of the other boxes.  The HMC team had mutliple test teams run into a bug where they had more than one user attempt to access KVM and encounter this bug.  The P9 HMC is completely graphically menu driven, so they are going to heavily depend on KVM on their boxes.  They have stated this is a GA gate for our GA which is less than a month away.

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/25231 is the upstream commit

**Comment by gtmills** [comment]
Did the upstream change, https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/25231  apply cleanly?

**Review by gtmills — APPROVED** [review]
Looks like just a cherry pick of https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/25231 
I am good here.

**Pull request merged**
