### PR TITLE
1050: Redfish : Look for OperationalStatus for the memory Health

### PR DESCRIPTION
**Pull request by ChicagoDuan**
Look for OperationalStatus for the memory Health.
When functional is false, health is critical.
When functional is true, health is ok.

No upstream commit. 1020 PR: https://github.com/ibm-openbmc/bmcweb/pull/152

Tested: Validator passes.
Set the dimm0 OperationalStatus to false, and see the health: curl -k -H "X-Auth-Token: $token" -X GET
https://${bmc}/redfish/v1/Systems/system/Memory/dimm0 {
  "Status": {
    "Health": "Critical",
    "State": "Enabled"
  }
}

Signed-off-by: Chicago Duan <duanzhijia01@inspur.com>

### CODE REVIEW

**Comment by gtmills** [comment]
@ChicagoDuan Why can't this part go upstream? 

```
    "LocationCode", locationCode, "Functional", functional);
        
 ...       
        
        
    if (functional != nullptr)
    {
        if (!*functional)
        {
            aResp->res.jsonValue[jsonPtr]["Status"]["Health"] = "Critical";
        }
    }



```

**Comment by ChicagoDuan** [comment]
> @ChicagoDuan Why can't this part go upstream?
> 
> ```
>     "LocationCode", locationCode, "Functional", functional);
>         
>  ...       
>         
>         
>     if (functional != nullptr)
>     {
>         if (!*functional)
>         {
>             aResp->res.jsonValue[jsonPtr]["Status"]["Health"] = "Critical";
>         }
>     }
> ```

When these PRs were first submitted to 1020 branch, Vishwa and I had some discussions about why we didn't push HealthRollUp-related PRs upstream. Because these do not conform to the upstream health status, they will not be accepted.

**Comment by gtmills** [comment]
```
    "LocationCode", locationCode, "Functional", functional);
        
 ...       
        
        
    if (functional != nullptr)
    {
        if (!*functional)
        {
            aResp->res.jsonValue[jsonPtr]["Status"]["Health"] = "Critical";
        }
    }
```

Looks like the very standard map Functional to Status Health.. 
Can that part these 10 lines go upstream?

**Comment by ChicagoDuan** [comment]
> Looks like the very standard map Functional to Status Health.. Can that part these 10 lines go upstream?

I saw your discussion with Ed about health and healthrollup on discord. It seems that Ed didn't agree. 
https://discord.com/channels/775381525260664832/855566794994221117/1075850722115063928

**Review by gtmills — APPROVED** [review]

**Pull request merged**
