### PR TITLE
Update Redfish schemas to 2022.2 and sort alphabetically

### PR DESCRIPTION
**Pull request by fnichols3**
This is the first part of https://w3.rchland.ibm.com/projects/bestquest/?defect=SW551681

This is a couple of upstream changes: 
1.  https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57360 Move to 2022.2
2. https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57407/15 Sort schema list alphabetically

New versions of the DMTF schema pack seem to make this list parse in less-than-ideal order.  Previously, the schema pack zip file had an order that was at least semi-alphabetical, but 2022.2 seems to cause that to change.

This commit makes the update_schemas.py script explicitly alphabetize the list.  This changes the order of two keys that have common prefixes, but leaves the rest of the order the same.  Both are arguably correct.

This commit also exposes that this script seemed to have lots of problems in its version number detection logic.  To make all this work properly, a fairly invasive change is required.

For testing, I used the Jenkins Redfish Validator. The tests passed.

This PR was merged from upstream and I had to add OEM schemas. This change also brought in additional DMTF schemas.

### CODE REVIEW

**Comment by gtmills** [comment]
add to approvelist

**Comment by gtmills** [comment]
jenkins run tests please

**Comment by gtmills** [comment]
@fnichols3 Can you add a "Tested" statement to your PR message ? 
Can you describe more, what changes this is? This is more than just [Sort schema list alphabetically](https://github.com/ibm-openbmc/bmcweb/pull/446/commits/cc45b8cff5ecfdbba67fdff9f38baa0b6c063021)

**Comment by fnichols3** [comment]
For testing, I used the Jenkins Redfish Validator (Build #1057, Oct 13, 2022, 11:21:22 AM). The tests passed.
I will get help to learn how to update the PR message.

**Review by sbteeks — APPROVED** [review]
Looks good

**Review by gtmills — APPROVED** [review]

**Pull request merged**
