### PR TITLE
1050: Implement LocationIndicatorActive for Memory resource

### PR DESCRIPTION
**Pull request by lxwinspur**
- Add the getLocationIndicatorActive method and the setLocationIndicatorActive method to bmcweb to support the LocationIndicatorActive property for memory.

Tested: Validator passes
curl -k -H "X-Auth-Token: $token" -X GET
https://${bmc}/redfish/v1/Systems/system/Memory/dimm0 {
  "@odata.id": "/redfish/v1/Systems/system/Memory/dimm0",
  "@odata.type": "#Memory.v1_11_0.Memory",
  "Id": "dimm0",
  "LocationIndicatorActive": false,
...
}

curl -k -H "X-Auth-Token: $token" -X PATCH -d
'{"LocationIndicatorActive":true}'
https://${bmc}/redfish/v1/Systems/system/Memory/dimm0

curl -k -H "X-Auth-Token: $token" -X GET
https://${bmc}/redfish/v1/Systems/system/Memory/dimm0 {
  "@odata.id": "/redfish/v1/Systems/system/Memory/dimm0",
  "@odata.type": "#Memory.v1_11_0.Memory",
  "Id": "dimm0",
  "LocationIndicatorActive": true,
...
}

upstream commit: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/37310

### CODE REVIEW

**Comment by gtmills** [comment]
@lxwinspur What is the upstream commit here?

**Comment by gtmills** [comment]
Looks like https://gerrit.openbmc.org/c/openbmc/bmcweb/+/37310 is the upstream commit

**Review by gtmills — APPROVED** [review]

**Comment by lxwinspur** [comment]
> Looks like https://gerrit.openbmc.org/c/openbmc/bmcweb/+/37310 is the upstream commit

Ah, Yes, Sorry forgot to add the upstream link.

**Comment by gtmills** [comment]
@lxwinspur Can you address the merge conflicts here and this can go? 
https://github.com/ibm-openbmc/bmcweb/pull/542 was a huge PR that caused these. 

Thanks!

**Pull request merged**
