### PR TITLE
1030: Fix environment metrics should chassis association

### PR DESCRIPTION
**Pull request by lxwinspur**
This adds the chassis association to the environment metric fans to ensure the fans belong to that chassis. E.g. CEC fans don't show up for i/o expansion drawer chassis 

Defect: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=457136
Port to 1020, 1040
The 1050 will be separate

Upstream is https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57715

resolved: https://github.com/ibm-openbmc/dev/issues/3619

### CODE REVIEW

**Comment by lxwinspur** [comment]
@gtmills 
I don't have the environment to test this issue.

**Comment by gtmills** [comment]
This looked good. non-CEC chassis:
```
{
"@odata.id": "/redfish/v1/Chassis/chassis15873/EnvironmentMetrics",
"@odata.type": "#EnvironmentMetrics.v1_1_0.EnvironmentMetrics",
"Id": "EnvironmentMetrics",
"Name": "Chassis Environment Metrics",
"PowerLimitWatts": {
"AllowableMax": 6111,
"AllowableMin": 3889,
"ControlMode": "Disabled",
"SetPoint": 0
},
"PowerWatts": {
"@odata.id": "/redfish/v1/Chassis/chassis15873/Sensors/total_power",
"DataSourceUri": "/redfish/v1/Chassis/chassis15873/Sensors/total_power",
"Reading": 749.0
}
}
```

vs CEC chassis:
```
{
"@odata.id": "/redfish/v1/Chassis/chassis/EnvironmentMetrics",
"@odata.type": "#EnvironmentMetrics.v1_1_0.EnvironmentMetrics",
"FanSpeedsPercent": [
{
"DataSourceUri": "/redfish/v1/Chassis/chassis/Sensors/fan0_1",
"DeviceName": "Chassis Fan #fan0_1",
"SpeedRPM": 4237.0
},
{
"DataSourceUri": "/redfish/v1/Chassis/chassis/Sensors/fan0_0",
"DeviceName": "Chassis Fan #fan0_0",
"SpeedRPM": 4134.0
},

```

**Review by gtmills — APPROVED** [review]

**Comment by gtmills** [comment]
@lxwinspur Please make sure this is addressed in https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57715

**Comment by gtmills** [comment]
@lxwinspur Can you do a separate 1050 PR for this?

**Comment by lxwinspur** [comment]
> @lxwinspur Please make sure this is addressed in https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57715

@gtmills 
I think upstream patch is works fine in 1050 branch, could you test it?

**Pull request merged**
