### PR TITLE
Fix SNMP invalid Destination error

### PR DESCRIPTION
**Pull request by raviteja-b**
This commit handles invalid SNMP destination error

Tested by:
Configure SNMP with invalid destination IP address '{"Destination": "snmp://10.6.6.256:162",
  "SubscriptionType": "SNMPTrap", "Protocol": "SNMPv2c"}'

Change-Id: I88f81a79a6665a7adc654e138b4f07ce321898a4

### CODE REVIEW

**Comment by raviteja-b** [comment]
upstream fix: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/67123

**Comment by sunharis** [comment]
@raviteja-b CI failure needs a fix - probably caused due to some difference between upstream and downstream code base

**Comment by raviteja-b** [comment]
jenkins run test please

**Comment by raviteja-b** [comment]
> @raviteja-b CI failure needs a fix - probably caused due to some difference between upstream and downstream code base

yes there too many differences b/w upstream and downstream in handling destination URI
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/65645

**Review by sunharis — APPROVED** [review]

**Comment by raviteja-b** [comment]
@gtmills can you please approve this PR

**Review by gtmills — APPROVED** [review]

**Pull request closed without merging**
