### PR TITLE
Location Code For PCIeSlots, Fans and Power Supplies

### PR DESCRIPTION
**Pull request by santoshpuranik**
This PR adds location code information for PcieSlots, Fans and PowerSupplies. Upstream commits are here:

https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/46591 for PcieSlots
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/41086 for Fans
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40326 for PowerSupplies

### CODE REVIEW

**Comment by santoshpuranik** [comment]
I'll update testing results here shortly

**Comment by geissonator** [comment]
add to approvelist

**Comment by gtmills** [comment]
Would like to see testing @santoshpuranik but looks reasonable

**Comment by gtmills** [comment]
For next time, please use a more descriptive branch name e.g. add-location-to-pcieslots-fans-powersupplies or add-location-code-to-inventory-items or something like that (doesn't have to be that long)

**Comment by santoshpuranik** [comment]
Tested this on Rainier:

```
curl -k -H "X-Auth-Token: $bmc_token" -D get.txt -X GET https://$bmc/redfish/v1/Chassis/chassis/PowerSubsystem/PowerSupplies/powersupply0
{
  "@odata.id": "/redfish/v1/Chassis/chassis/PowerSubsystem/PowerSupplies/powersupply0",
  "@odata.type": "#PowerSupply.v1_0_0.PowerSupply",
  "EfficiencyRatings": [
    {
      "EfficiencyPercent": 90
    }
  ],
  "Id": "powersupply0",
  "Location": {
    "PartLocation": {
      "ServiceLabel": "U78DA.ND0.WZS004A-E0"
    }
  },
  "LocationIndicatorActive": false,
  "Manufacturer": "",
  "Model": "51E9",
  "Name": "powersupply0",
  "PartNumber": "03FP379",
  "SerialNumber": "1490T2",
  "SparePartNumber": "",
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  }
}
```
```
curl -k -H "X-Auth-Token: $bmc_token" -D get.txt -X GET https://$bmc/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0_1
{
  "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0_1/",
  "@odata.type": "#Fan.v1_0_0.Fan",
  "Id": "fan0_1",
  "Location": {
    "PartLocation": {
      "ServiceLabel": "U78DA.ND0.WZS004A-A0"
    }
  },
  "LocationIndicatorActive": false,
  "Manufacturer": "",
  "Model": "7B5G",
  "Name": "fan0_1",
  "PartNumber": "",
  "SerialNumber": "",
  "SparePartNumber": "02YK237",
  "SpeedPercent": {
    "@odata.id": "/redfish/v1/Chassis/chassis/Sensors/fan0_1/",
    "DataSourceUri": "/redfish/v1/Chassis/chassis/Sensors/fan0_1/",
    "Reading": 0.0
  },
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  }
}
```
```
❯ curl -k -H "X-Auth-Token: $bmc_token" -D get.txt -X GET https://$bmc/redfish/v1/Chassis/chassis/PCIeSlots
{
  "@odata.id": "/redfish/v1/Chassis/chassis/PCIeSlots",
  "@odata.type": "#PCIeSlots.v1_4_1.PCIeSlots",
  "Id": "PCIeSlots",
  "Name": "PCIe Slot Information",
  "Slots": [
    {
      "HotPluggable": false,
      "Lanes": 0,
      "Location": {
        "PartLocation": {
          "ServiceLabel": "U78DA.ND0.WZS004A-P1-C0"
        }
      },
      "LocationIndicatorActive": false
    },
    {
      "HotPluggable": false,
      "Lanes": 0,
      "Location": {
        "PartLocation": {
          "ServiceLabel": "U78DA.ND0.WZS004A-P1-C1"
        }
      },
      "LocationIndicatorActive": false
    },
....
....
```

**Comment by santoshpuranik** [comment]
I also ran the validator against a Rainier system with this change - Looked good except for a known error with Bios attributes.

**Review by gtmills — APPROVED** [review]

**Pull request merged**
