### PR TITLE
Add LicenseService support

### PR DESCRIPTION
**Pull request by raviteja-b**
This commit implements LicenseService support and LicenseRegistry support
This is IBM only Downstream implementation 

Tested By: 
POST https://{bmc}/redfish/v1/LicenseService/Licenses -d '{"LicenseString": "CA1F000000412C200000gyLzCwvb3rRUTg"}'
 { 
  "error": { "@Message.ExtendedInfo": [ { "@odata.type": "#Message.v1_0_0.Message", "Message": "Indicates that the license is not applicable to the target.", "MessageArgs": null, "MessageId": "License.1.0.0.notApplicableToTarget", "Resolution": "None.", "Severity": "Critical" } ], "code": "License.1.0.0.notApplicableToTarget", "message": "Indicates that the license is not applicable to the     target." }
 }  

POST https://{bmc}/redfish/v1/LicenseService/License -d '{"LicenseString": "CA1F000000412C200000gyLzCwvb3rRUT1"}' 
{ 
"error": { "@Message.ExtendedInfo": [ { "@odata.type": "#Message.v1_0_0.Message", "Message": "The content of the license was not recognized, is corrupted, or is invalid.", "MessageArgs": null, "MessageId": "License.1.0.0.InvalidLicense", "Resolution": "None.", "Severity": "Critical" } ], "code": "License.1.0.0.InvalidLicense", "message": "The content of the license was not recognized, is corrupted, or is invalid." }
 } 

POST https://{bmc}/redfish/v1/LicenseService/Licenses -d '{"LicenseString": "CA1F000000412C200000gyLzCwvb3rRUT2"}' 
{
 "error": { "@Message.ExtendedInfo": [ { "@odata.type": "#Message.v1_0_0.Message", "Message": "Failed to install the license. Reason: ActivationFailed", "MessageArgs": [ "ActivationFailed" ], "MessageId": "License.1.0.0.InstallFailed", "Resolution": "None.", "Severity": "Critical" } ], "code": "License.1.0.0.InstallFailed", "message": "Failed to install the license. Reason: ActivationFailed" } 
 } 

POST https://{bmc}/redfish/v1/LicenseService/Licenses -d '{"LicenseString": "CA1F000000412C200000gyLzCwvb3rRUT2"}' 
{ 
"[LicenseInstalled@Message.ExtendedInfo](mailto:LicenseInstalled@Message.ExtendedInfo)": [ { "@odata.type": "#Message.v1_0_0.Message", "Message": "The license has been installed CA1F000000412C200000gyLzCwvb3rRUT2", "MessageArgs": [ "CA1F000000412C200000gyLzCwvb3rRUT2" ], "MessageId": "License.1.0.0.LicenseInstalled", "Resolution": "None.", "Severity": "OK" } ]
 } 

Redfish validator Passed

### CODE REVIEW

**Comment by gtmills** [comment]
@raviteja-b What commits were these orginally? Is this going upstream, why not? 
Can you add more to the commit msg about what this all does and how it was tested?

**Comment by raviteja-b** [comment]
> @raviteja-b What commits were these orginally? Is this going upstream, why not?
> Can you add more to the commit msg about what this all does and how it was tested?

We have decided to keep this Downstream only when we implemented this license feature.
yes we can push to upstream but it needs little more rework and D-bus interfaces discussions

**Comment by rfrandse** [comment]
jenkins run tests please

**Comment by raviteja-b** [comment]
jenkins run tests please

**Review by sunharis — APPROVED** [review]
Changes looks good to me.

**Comment by gtmills** [comment]
> We have decided to keep this Downstream only when we implemented this license feature.
yes we can push to upstream but it needs little more rework and D-bus interfaces discussions

Do we have a timeline to do so?

**Review by gtmills — APPROVED** [review]

**Pull request merged**
