### PR TITLE
[DO NOT MERGE] Remove bmc ipv6 support

### PR DESCRIPTION
**Pull request by nkotania**
Its a part of 1050 rebase, changes from https://github.com/ibm-openbmc/bmcweb/commit/bb36397648d71ef144d6c0f8247c1e4f67689d1b

* Remove bmc ipv6 support

This commit removes the front end support for IPv6 configuration
on the bmc ethernet interfaces, while the dbus interfaces and networkd
has the code in place. This change removes the redfish GET & PATCH support
for IPv6 and will not allow user to configure static ipv6 address,
enable/disable dhcp v6 on ethernet interfaces, patch default gateway.

The following changes are made in this commit:
1. Remove IPv6 data from the redfish GET response data
2. Return "Not supported" response when user enables DHCPv6
3. Return "Not supported" response when user sends PATCH command
   on ethernet interfaces with IPv6 parameters

Tested By:
PATCH -d '{"IPv6StaticAddresses":[{"Address": "<>", "PrefixLength": <>}], \
"IPv4StaticAddresses":[{"Address": "<>","SubnetMask": "<>","Gateway":"<>"}]}' \
https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth1

PATCH -d '{"DHCPv6": {"OperatingMode":"Disabled"}, \
"IPv4StaticAddresses":[{"Address": "<>","SubnetMask": "<>","Gateway":"<>"}]}' \
https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth1
 => Returns action not supported

### CODE REVIEW

**Review by sunharis — APPROVED** [review]

**Comment by sunharis** [comment]
jenkins run tests please

**Review by asmithakarun — APPROVED** [review]

**Comment by nkotania** [comment]
> Can one of the admins verify this patch?

Verified and working as expected.

**Comment by gtmills** [comment]
add to approvelist

**Comment by sunharis** [comment]
> We are planning to pull complete IPv6 support into 1050. I guess we don't need this PR, lets keeps this PR on hold for sometime

Agree. Thanks Ravi. @rfrandse Please do not merge this PR, since we have IPv6 support on 1050 plan.

**Review by gtmills — CHANGES_REQUESTED** [review]
In the comments:

 raviteja-b commented Jan 25, 2023 •

We are planning to pull complete IPv6 support into 1050.
I guess we don't need this PR, lets keeps this PR on hold for sometime.

so I think this one doesn't need merged and we will wait and see what happens

**Comment by gtmills** [comment]
I am going to close. Please reopen and rebase if this is needed but as I understand 1050 IPV6 support, we don't need this PR.

**Pull request closed without merging**
