### PR TITLE
Fix SNMP invalid Destination error

### PR DESCRIPTION
**Pull request by raviteja-b**
This commit handles invalid SNMP destination error

Tested by:
Configure SNMP with invalid destination IP address '{"Destination": "snmp://10.6.6.256:162",
"SubscriptionType": "SNMPTrap", "Protocol": "SNMPv2c"}'

### CODE REVIEW

**Comment by raviteja-b** [comment]
this already got approved https://github.com/ibm-openbmc/bmcweb/pull/776 
I have delete forked repo by mistake.

**Review by sunharis — APPROVED** [review]

**Comment by sunharis** [comment]
Please fix the format error & mention the upstream commit id

**Comment by raviteja-b** [comment]
upstream commit: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/67123

**Review by sunharis — APPROVED** [review]

**Review by gtmills — APPROVED** [review]

**Comment by raviteja-b** [comment]
Fixes: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=580484

**Pull request merged**
