### PR TITLE
1050 Add support for redfish StopBootOnFault

### PR DESCRIPTION
**Pull request by lxwinspur**
This commit is added get and set for StopBootOnFault Policy. The StopBootOnFault is defined in ComputerSystem(boot). It contains two values "Never" and "AnyFault".

ref:https://redfish.dmtf.org/schemas/v1/ComputerSystem.v1_15_0.json

Tested:

1.Validator passes

2.doGet method to get StopBootOnFault.

curl -k -H "X-Auth-Token: $token" -X GET
https://${bmc}/redfish/v1/Systems/system
{
  "@odata.id": "/redfish/v1/Systems/system",
  "@odata.type": "#ComputerSystem.v1_16_0.ComputerSystem",
  "Boot": {
    ...
    "RemainingAutomaticRetryAttempts": 3,
    "StopBootOnFault": "Never",
    "TrustedModuleRequiredToBoot": "Disabled"
  }
  ...
}

3. doPatch method set the "StopBootOnFault" property to AnyFault or Never and report error when set to other values

curl -k -H "X-Auth-Token: $token" -X PATCH -d
'{ "Boot" :{"StopBootOnFault":"AnyFault"}}'
https://${bmc}/redfish/v1/Systems/system

A few seconds later,
curl -k -H "X-Auth-Token: $token" -X GET
https://${bmc}/redfish/v1/Systems/system
{
  "@odata.id": "/redfish/v1/Systems/system",
  "@odata.type": "#ComputerSystem.v1_16_0.ComputerSystem",
  "Boot": {
    ...
    "RemainingAutomaticRetryAttempts": 3,
    "StopBootOnFault": "AnyFault",
    "TrustedModuleRequiredToBoot": "Disabled"
  }
  ...
}

Signed-off-by: George Liu <liuxiwei@inspur.com>

### CODE REVIEW

**Comment by lxwinspur** [comment]
@gtmills @baemyung 
Please review this PR

**Comment by gtmills** [comment]
jenkins run tests please

**Comment by gtmills** [comment]
> @gtmills @baemyung
Please review this PR

Please add reviewers :)

**Comment by gtmills** [comment]
What is the upstream commit here?

**Comment by geissonator** [comment]
The initial design didn't require a Redfish API here (https://grok.openbmc.org/xref/openbmc/docs/designs/fail-boot-on-hw-error.md?r=f4febd00#41) but looks like we got it added. Nice! No reason this can't be sent to upstream gerrit first.

**Comment by lxwinspur** [comment]
> > @gtmills @baemyung
> > Please review this PR
> 
> Please add reviewers :)

I do not have permission to add reviewers.

**Comment by gtmills** [comment]
@lxwinspur Can you send upstream?

**Comment by gtmills** [comment]
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/44175 is upstream. Can we keep going on that?

**Review by gtmills — APPROVED** [review]

**Pull request merged**
