### PR TITLE
Redfish : Add Firmware Version to Power Supplies

### PR DESCRIPTION
**Pull request by ChicagoDuan**
Add Firmware Version to Power Supplies schema
https://redfish.dmtf.org/schemas/v1/PowerSupply.v1_3_0.json

Tested : Validator passes.
curl -k -H "X-Auth-Token: $token" -XGET
https://${bmc}/redfish/v1/Chassis/chassis/PowerSubsystem/PowerSupplies/powersupply0
{
  "@odata.id": "/redfish/v1/Chassis/chassis/PowerSubsystem/PowerSupplies/powersupply0",
  "@odata.type": "#PowerSupply.v1_0_0.PowerSupply",
  "EfficiencyRatings": [
    {
      "EfficiencyPercent": 90
    }
  ],
  "FirmwareVersion": "test-powersupplyversion-123",
  "Id": "powersupply0",
  "LocationIndicatorActive": false,
  "Manufacturer": "",
  "Model": "",
  "Name": "powersupply0",
  "PartNumber": "",
  "SerialNumber": "",
  "SparePartNumber": "",
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  }
}

Signed-off-by: Chicago Duan <duanzhijia01@inspur.com>

### CODE REVIEW

**Comment by gtmills** [comment]
jenkins run tests please

**Comment by gtmills** [comment]
Can this be pushed upstream?

**Comment by ChicagoDuan** [comment]
> Can this be pushed upstream?

It has been pushed upstream : https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40326

**Review by gtmills — APPROVED** [review]

**Comment by bjwyman** [comment]
> "FirmwareVersion": "test-powersupplyversion-123",

That is more readable than what I usually see in `/sys/kernel/debug/pmbus/hwmon*/cffps*/fw_version` or what ends up on D-Bus. It is supposed to be ASCII, but sometimes it doesn't look right the way the power supplies return it.

**Review by bjwyman — APPROVED** [review]
Looks reasonable to me, but I normally do not review bmcweb code.

Reference from D-Bus introspect, in SIMICS, with fake version set:
```
...
xyz.openbmc_project.Inventory.Item                    interface -         -                                        -
.Present                                              property  b         true                                     emits-change writable
.PrettyName                                           property  s         "powersupply0"                           emits-change writable
xyz.openbmc_project.Inventory.Item.PowerSupply        interface -         -                                        -
xyz.openbmc_project.Object.Enable                     interface -         -                                        -
.Enabled                                              property  b         false                                    emits-change writable
xyz.openbmc_project.Software.Version                  interface -         -                                        -
.Purpose                                              property  s         "xyz.openbmc_project.Software.Version.V��� emits-change writable
.Version                                              property  s         "313033323330"                           emits-change writable
xyz.openbmc_project.State.Decorator.OperationalStatus interface -         -                                        -
.Functional                                           property  b         true                                     emits-change writable
root@srainier2s2u:~# 
```

**Pull request merged**
