### PR TITLE
Fix LampTest and get/setSAI

### PR DESCRIPTION
**Pull request by lxwinspur**
Fix PartitionSystemAttentionIndicator / PlatformSystemAttentionIndicator OEM
refer: https://github.com/ibm-openbmc/dev/issues/3519

After enabled both -Dibm-sai and -Dibm-lamp-test Lamp Test no longer works
refer: https://github.com/ibm-openbmc/dev/issues/3520

Signed-off-by: George Liu <liuxiwei@inspur.com>

### CODE REVIEW

**Comment by gtmills** [comment]
jenkins run tests please

**Comment by gtmills** [comment]
@lxwinspur Did the Redfish Validator pass here?

**Comment by lxwinspur** [comment]
@gtmills 
https://github.com/ibm-openbmc/bmcweb/pull/276
is this the same bug?

**Comment by santoshpuranik** [comment]
> @gtmills #276 is this the same bug?

Yes, it is. I wasn't aware you were looking at this too! Sorry about the miscommunication.

**Comment by santoshpuranik** [comment]
I guess we can close this PR

**Comment by lxwinspur** [comment]
> I guess we can close this PR

Okay, I will close it.

**Pull request closed without merging**
