### PR TITLE
1050: Fix fan resources in the ThermalSubsystem info

### PR DESCRIPTION
**Pull request by lxwinspur**
The ThermalSubsystem info not be based on the tach sensors but rather the FRUs.

Resloved: https://github.com/ibm-openbmc/dev/issues/3621

### CODE REVIEW

**Comment by spinler** [comment]
I tried this:

this part looks good:
```
 /redfish/v1/Chassis/chassis/ThermalSubsystem/Fans
{
  "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans",
  "@odata.type": "#FanCollection.FanCollection",
  "Description": "The collection of Fan resource instances chassis",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan1"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan2"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan3"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan4"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan5"
    }
  ],
  "Members@odata.count": 6,
  "Name": "Fan Collection"
}
```
But this fails:
```
/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0
{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "#Message.v1_1_1.Message",
        "Message": "The requested resource of type Fan named 'fan0' was not found.",
        "MessageArgs": [
          "Fan",
          "fan0"
        ],
        "MessageId": "Base.1.13.0.ResourceNotFound",
        "MessageSeverity": "Critical",
        "Resolution": "Provide a valid resource identifier and resubmit the request."
      }
    ],
    "code": "Base.1.13.0.ResourceNotFound",
    "message": "The requested resource of type Fan named 'fan0' was not found."
  }
}
```

it looks like the fan sensor still shows up:
```
/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0_0
{
  "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0_0",
  "@odata.type": "#Fan.v1_3_0.Fan",
  "Id": "fan0_0",
  "Location": {
    "PartLocation": {
      "ServiceLabel": "U78DB.ND0.1234567-A0"
    }
  },
  "LocationIndicatorActive": false,
  "Manufacturer": "Delta",
  "Model": "7B5F",
  "Name": "fan0_0",
  "PartNumber": "02YK323",
  "SerialNumber": "YL12JP1C1234",
  "SparePartNumber": "02YK323",
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  }
}
```

I checked 1030, fan0 does work there.

**Comment by lxwinspur** [comment]
Thanks a lot, @spinler 
I updated this issue again, But I don't have a test environment with 1050, could you help me test it? Thank you!

**Comment by spinler** [comment]
Output looks good!
```
/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan4
{
  "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan4",
  "@odata.type": "#Fan.v1_3_0.Fan",
  "Id": "fan4",
  "Location": {
    "PartLocation": {
      "ServiceLabel": "U78DB.ND0.1234567-A4"
    }
  },
  "LocationIndicatorActive": false,
  "Manufacturer": "Delta",
  "Model": "7B5F",
  "Name": "fan4",
  "PartNumber": "02YK323",
  "SerialNumber": "YL12JP1C1234",
  "SparePartNumber": "02YK323",
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  }
```

**Review by spinler — APPROVED** [review]
I'm not that experienced at reviewing bmcweb changes but it looks good to me.

**Comment by spinler** [comment]
Can this just go upstream?

**Comment by lxwinspur** [comment]
> Can this just go upstream?

I have a topic to increase the functionality of Fan, but unfortunately, the upstream response is slow, and several commits have been abandoned.

Let me push this topic again next week, but really don't want to waste too much time upstream.

https://gerrit.openbmc.org/q/topic:redfish-fan

**Review by gtmills — APPROVED** [review]

**Comment by spinler** [comment]
> Can this just go upstream?
> 
> I have a topic to increase the functionality of Fan, but unfortunately, the upstream response is slow, and several commits have been abandoned.
> 
> Let me push this topic again next week, but really don't want to waste too much time upstream.
> 
> https://gerrit.openbmc.org/q/topic:redfish-fan

No problem, just want to make sure that if the code does go in upstream it has these changes.

**Pull request merged**
