### PR TITLE
Modify fan related bugs

### PR DESCRIPTION
**Pull request by zhanghaodi**
Modify ThermalSubsystem fan objects from sensors-based to
fan inventory FRU.

Signed-off-by: Albert Zhang <zhanghaodi@inspur.com>

### CODE REVIEW

**Comment by gtmills** [comment]
jenkins run tests please

**Comment by msbarth** [comment]
There's updates to inventory's `associations.json` that must go in along with this.

**Comment by gtmills** [comment]
@zhanghaodi What is the status of upstream here?

**Comment by gtmills** [comment]
Going to default to Matt here who tested this.

**Review by gtmills — APPROVED** [review]

**Pull request merged**
