### PR TITLE
Redfish: Implement HealthRollup in chassis schema

### PR DESCRIPTION
**Pull request by ChicagoDuan**
The health status of the current CPUs and powersupplies will not rollup
to chassis. This submission implements rollup of the health status of
CPUs and powersupplies to chassis.

Tested:
We need add the xyz.openbmc_project.Inventory.Item.Global interface to the chassis.
I create a critical association of powersupply1 using the same method as phosphor-logging:
https://github.com/openbmc/phosphor-logging/blob/76198a2ea2e3deb14078e0d3dd3932b657ddd9b8/extensions/openpower-pels/service_indicators.cpp#L83

Then the chassis HealthRollup will become critical:
curl -k -H "X-Auth-Token: $token" -X GET   https://${bmc}/redfish/v1/Chassis/chassis
"Status": {
    "Health": "Critical",
    "HealthRollup": "Critical",
    "State": "Enabled"
  },

Signed-off-by: Chicago Duan <duanzhijia01@inspur.com>

### CODE REVIEW

**Comment by ChicagoDuan** [comment]
Hi @gtmills @lkammath 
For the HealthRollup. Because logging will creates the critical associations, we only need to add inventories to chassis.hpp to implement the healthrollup of chassis.

For the Health. The CPU , Fan and powersupply will look for the OperationalStatus to to determine the health status, so we don't need to do anything.

**Comment by ChicagoDuan** [comment]
Make the Health of chassis unaffected by child inventories.  

Now the chassis Health will be "OK" and HealthRollup will be "Critical":
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis
"Status": {
"Health": "OK",
"HealthRollup": "Critical",
"State": "Enabled"
},

**Comment by patelabhishek9893** [comment]
https://github.com/ibm-openbmc/bmcweb/pull/81/files#diff-a68f9c2dffb54698897597083bdaef7666589ebadef3a360f650f9a6d192fcc5R218
one line 218:
Common error.  Please read fix the common errors
https://github.com/openbmc/bmcweb/blob/master/COMMON_ERRORS.md#12-imprecise-matching

**Comment by ChicagoDuan** [comment]
> https://github.com/ibm-openbmc/bmcweb/pull/81/files#diff-a68f9c2dffb54698897597083bdaef7666589ebadef3a360f650f9a6d192fcc5R218
> one line 218 of file redfish-core/lib/chassis.hpp
> Common error. Please read fix the common errors
> https://github.com/openbmc/bmcweb/blob/master/COMMON_ERRORS.md#12-imprecise-matching

Hi @patelabhishek9893 , are you talking about this line?:
https://github.com/ibm-openbmc/bmcweb/blob/1020/redfish-core/lib/chassis.hpp#L218
This line was not added by this commit.

**Comment by patelabhishek9893** [comment]
> > https://github.com/ibm-openbmc/bmcweb/pull/81/files#diff-a68f9c2dffb54698897597083bdaef7666589ebadef3a360f650f9a6d192fcc5R218
> > one line 218 of file redfish-core/lib/chassis.hpp
> > Common error. Please read fix the common errors
> > https://github.com/openbmc/bmcweb/blob/master/COMMON_ERRORS.md#12-imprecise-matching
> 
> Hi @patelabhishek9893 , are you talking about this line?:
> https://github.com/ibm-openbmc/bmcweb/blob/1020/redfish-core/lib/chassis.hpp#L218
> This line was not added by this commit.

yes but sill is good to fix that
your code look good to me

**Comment by patelabhishek9893** [comment]
can you please resolve the code conflict?

**Comment by ChicagoDuan** [comment]
> > > https://github.com/ibm-openbmc/bmcweb/pull/81/files#diff-a68f9c2dffb54698897597083bdaef7666589ebadef3a360f650f9a6d192fcc5R218
> > > one line 218 of file redfish-core/lib/chassis.hpp
> > > Common error. Please read fix the common errors
> > > https://github.com/openbmc/bmcweb/blob/master/COMMON_ERRORS.md#12-imprecise-matching
> > 
> > 
> > Hi @patelabhishek9893 , are you talking about this line?:
> > https://github.com/ibm-openbmc/bmcweb/blob/1020/redfish-core/lib/chassis.hpp#L218
> > This line was not added by this commit.
> 
> yes but sill is good to fix that
> your code look good to me

There may be a lot of such code in bmcweb, and I will try to fix it upstream

**Comment by ChicagoDuan** [comment]
> can you please resolve the code conflict?

Sure, I can.

**Comment by ChicagoDuan** [comment]
Creat a new pull request: https://github.com/ibm-openbmc/bmcweb/pull/107

**Pull request closed without merging**
