### PR TITLE
Add the verification of chassisID

### PR DESCRIPTION
**Pull request by zhanghaodi**
At present,there is no verification of chassisID in the
...redfish/v1/Chassis/chassis/ThermalSubsystem/Fans directory.
In order to display this function correctly for multiple chassis,
add the verification of chassisID.

Signed-off-by: Albert Zhang <zhanghaodi@inspur.com>

### CODE REVIEW

**Comment by gtmills** [comment]
jenkins run tests please

**Comment by gtmills** [comment]
@zhanghaodi Is there an upstream change for this?

**Comment by gtmills** [comment]
Does this fix a issue?

**Comment by zhanghaodi** [comment]
@gtmills 
In https://github.com/ibm-openbmc/dev/issues/3513,
This solves the problem that spinler said, in getValidFan, it is determined that fans belong to the corresponding chassis.

**Comment by gtmills** [comment]
CI fail
```
FAILED: bmcweb.p/src_webserver_main.cpp.o 
c++ -Ibmcweb.p -I. -I.. -I../include -I../redfish-core/include -I../redfish-core/lib -I../http -I/usr/local/include -flto=auto -fdiagnostics-color=never -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++20 -fno-rtti -g -fno-lto -DBMCWEB_ENABLE_BASIC_AUTHENTICATION -DBMCWEB_ENABLE_COOKIE_AUTHENTICATION -DBMCWEB_ENABLE_EVENT_SUBSCRIPTION_WEBSOCKET -DBMCWEB_ENABLE_HOST_SERIAL_WEBSOCKET -DBMCWEB_ENABLE_SSL -DBMCWEB_ENABLE_KVM -DBMCWEB_ENABLE_MUTUAL_TLS_AUTHENTICATION -DWEBSERVER_ENABLE_PAM -DBMCWEB_ENABLE_REDFISH -DBMCWEB_ENABLE_DBUS_REST -DBMCWEB_ENABLE_SESSION_AUTHENTICATION -DBMCWEB_ENABLE_STATIC_HOSTING -DBMCWEB_ENABLE_VM_WEBSOCKET -DBMCWEB_ENABLE_XTOKEN_AUTHENTICATION -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wconversion -Wsign-conversion -Wno-attributes -Wno-stringop-overflow -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wunused-parameter -Wnull-dereference -Wdouble-promotion -Wformat=2 -DBMCWEB_ENABLE_LOGGING -DBMCWEB_ENABLE_DEBUG -DBMCWEB_ALLOW_DEPRECATED_POWER_THERMAL -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DBOOST_BEAST_USE_STD_STRING_VIEW -DBOOST_ASIO_NO_DEPRECATED -DBOOST_NO_RTTI -DBOOST_NO_TYPEID -DBOOST_URL_STANDALONE -DBOOST_URL_HEADER_ONLY -DBOOST_ALLOW_DEPRECATED_HEADERS -DJSON_NOEXCEPTION -DBOOST_ASIO_DISABLE_THREADS -DBOOST_ALL_NO_LIB -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -MD -MQ bmcweb.p/src_webserver_main.cpp.o -MF bmcweb.p/src_webserver_main.cpp.o.d -o bmcweb.p/src_webserver_main.cpp.o -c ../src/webserver_main.cpp
In file included from ../redfish-core/include/redfish.hpp:28,
                 from ../src/webserver_main.cpp:25:
../redfish-core/include/../lib/fan.hpp: In lambda function:
../redfish-core/include/../lib/fan.hpp:235:33: error: ‘chassisID’ was not declared in this scope; did you mean ‘chassisId’?
  235 |                     [asyncResp, chassisID, fanPath, connectionName](
      |                                 ^~~~~~~~~
      |                                 chassisId
../redfish-core/include/../lib/fan.hpp: In lambda function:
../redfish-core/include/../lib/fan.hpp:272:44: error: ‘chassisId’ is not captured
  272 |                         if (chassisName != chassisId)
      |                                            ^~~~~~~~~
../redfish-core/include/../lib/fan.hpp:235:67: note: the lambda has no capture-default
  235 |                     [asyncResp, chassisID, fanPath, connectionName](
      |                                                                   ^
../redfish-core/include/../lib/fan.hpp:209:27: note: ‘const string chassisId’ declared here
  209 |                 fansubtree) {
      |                           ^
```

**Comment by spinler** [comment]
@mikecgithub is going to drive the testing

**Comment by zhanghaodi** [comment]
@gtmills 
CI failed has been resolved and resubmitted.

**Comment by gtmills** [comment]
Should we wait to merge this until @mikecgithub tests?

**Comment by mikecgithub** [comment]
I have been testing this, but the driver doesn't report health properties for MEX cabinets. I'm testing a fix that ignores the failed D-Bus calls (EBADR) but currently I still only see the MEX fans. Once I figure out why I will update this PR.

**Comment by mikecgithub** [comment]
I have tested and confirmed this change works. If you run the following command:

 `curl -k -X GET https://service:0penBmc@<hostname>/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans
` 
 without this fix, you will get an incorrect list of fans:
 
 "Members": [
  {
    "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0/"
  },
  {
    "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan1/"
  },
  {
    "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan2/"
  },
  {
    "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan3/"
  },
  {
    "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan1/"
  },
  {
    "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan2/"
  },
  {
    "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan3/"
  },
  {
    "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan4/"
  }
],

Notice the duplication of fans. What we have here are the CEC fans (fan0-fan3) and MEX fans (fan1-fan4). After this PR is applied, this command:

`curl -k -X GET https://service:0penBmc@<hostname>/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans
` 
will report fans0-3, while this one:

 `curl -k -X GET https://service:0penBmc@<hostname>/redfish/v1/Chassis/chassis15363/ThermalSubsystem/Fans
` 
Will report fan1-fan4 from the MEX drawer.

I have a code fix which I may create a future PR for that is related to this change. What we observed is the MEX fans do not report the same driver health as CEC. When the D-Bus properties are queried, they come back with an asio error code set to 53 (EBADR). I have a fix to detect this and report "Unknown" which may be useful to the UI.

**Review by mikecgithub — APPROVED** [review]

**Comment by mikecgithub** [comment]
@zhanghaodi please apply the following patch to your PR as a755cbe will not compile for me:

-                    [asyncResp, chassisId, fanPath, connectionName](
+                    [asyncResp, chassisId, &fanList, fanPath, newPath, connectionName](

**Comment by zhanghaodi** [comment]
@mikecgithub 
This patch has been submitted.

**Review by mikecgithub — APPROVED** [review]

**Comment by mikecgithub** [comment]
Tested and confirmed b98bb correctly separates fans by chassisId. I will provide a subsequent fix that will allow querying individual fan paths without forwarding any error info caused by D-Bus queries.

**Comment by gtmills** [comment]
jenkins run tests please

**Review by gtmills — APPROVED** [review]
Defaulting to Mike here who tested

**Pull request merged**
