### PR TITLE
1050.power supply

### PR DESCRIPTION
**Pull request by lxwinspur**
These commits implement the Redfish PowerSupply schema and populate the PowerSupplyCollection members.
Include:
- Efficiency Percent
- FirmwareVersion
- Location
- LocationIndicatorActive
- Manufacturer
- Model
- PartNumber
- SerialNumber
- SparePartNumber
- Status

Upstream commits:
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/58924/17>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57668/25>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57669/17>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57670/14>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57765/23>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57671/9>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57672/9>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57673/9>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57709/7>
<https://gerrit.openbmc.org/c/openbmc/bmcweb/+/42221/11>

### CODE REVIEW

**Comment by gtmills** [comment]
jenkins run tests please

**Comment by gtmills** [comment]
@lxwinspur Can you add the upstream commits with the patch set number like I did above for the first one?

**Comment by gtmills** [comment]
@lxwinspur Any testing?

**Comment by lxwinspur** [comment]
> @lxwinspur Can you add the upstream commits with the patch set number like I did above for the first one?

Done

**Comment by lxwinspur** [comment]
@gtmills 
I will push a PR related to Fan after this commit is merged, Thanks.

**Pull request merged**
