### PR TITLE
Bump schemas and base registry

### PR DESCRIPTION
**Pull request by gtmills**
3 merged commits from upstream to move up schemas and base registry. 

1)  Pull in 2024.1 schemas

Redfish released 2024.1 in May.
https://www.dmtf.org/content/redfish-release-20241-now-available

"The bundle includes 29 schema updates and additional developer
resources." There was a request on the discord server to pull this in.

Changed 1 line scripts/update_schemas.py and reran the tool.

Tested: None. Inspection only. Picking up new schemas hasn't caused
problems in the past.

Upstream merged at
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/72172

2)  bump base registry to 1.18.1

72169 points out a mistake in 1.16 which is fixed in 1.18. Let's pull
1.18.1 in. 1.18.1 is the latest.

Changed 1 line in parse_registries.py and reran it.

Tested: None. In the past bumping these hasn't caused problems.

Upstream merged at https://gerrit.openbmc.org/c/openbmc/bmcweb/+/72173.

3) Update symlinks for 2024.1 

Wrote a quick bash script to update these symlinks.

These are versioned out in json schema directory[1].

The symlinks don't work without this update.

[1]: https://github.com/openbmc/bmcweb/tree/master/redfish-core/schema/dmtf/json-schema

Before:
cat static/redfish/v1/JsonSchemas/redfish-error/redfish-error.json
cat: static/redfish/v1/JsonSchemas/redfish-error/redfish-error.json: No
such file or directory

#1 pulled in 2024.1 but did not update these links. Long term update_schemas.py should do this. I figured fix it first, then add update_schemas.py support.

Upstream merged at https://gerrit.openbmc.org/c/openbmc/bmcweb/+/72281

### CODE REVIEW

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/bmcweb/pull/1011 needs to go first

**Comment by baemyung** [comment]
> #1011 needs to go first
I've fixed some of incorrect files (under `static/redfish/v1/JsonSchemas/*.son`) to the symlinks (`../../../../../redfish-core/schema/dmtf/`), and  #1011 is now ready for merge.

This PR may also need to apply the changes against the actual files (`../../../../../redfish-core/schema/dmtf/` rather than `static/redfish/v1/JsonSchemas/*.son`) if there are.

**Review by baemyung — APPROVED** [review]
This PR would need to be rebased on top of the latest #1011 (which uses the symlink).
For example, 
```
static/redfish/v1/JsonSchemas/AccelerationFunction/AccelerationFunction.json 
     -> ../../../../../redfish-core/schema/dmtf/json-schema/AccelerationFunction.v1_0_4.json
```

With such changes, this would be good

**Comment by gtmills** [comment]
@baemyung  Is this what you expect?

**Review by jeaaustx — APPROVED** [review]

**Comment by baemyung** [comment]
> @baemyung Is this what you expect?

I think some of links are incorrect.
For example,

```
 ./static/redfish/v1/JsonSchemas/AllowDeny/AllowDeny.json -> ../../../../../redfish-core/schema/dmtf/json-schema/AllowDeny.v1_0_2.json
```

However, the actual file version is v1_0_3.
```
./redfish-core/schema/dmtf/json-schema/AllowDeny.v1_0_3.json
```

So, this will need to be 



[.../dmtf/json-schema/Application.v1_0_0.json → .../dmtf/json-schema/Application.v1_0_1.json](https://github.com/ibm-openbmc/bmcweb/pull/1013/files#diff-b8697a5a9abd00f9321457f2fd0c0e8d27d47800695ab79821b248b2fb25e464)

**Review by baemyung — APPROVED** [review]
It looks good to me

**Comment by baemyung** [comment]
Sorry, I accidentally checked the approval mark.  I'll look at this later after another push happens.

**Comment by baemyung** [comment]
Taking a same example ` ./static/redfish/v1/JsonSchemas/AllowDeny/AllowDeny.json`, it looks like the link is still pointing to `../../../../../redfish-core/schema/dmtf/json-schema/AllowDeny.v1_0_2.json`.

**Comment by baemyung** [comment]
I think - the script is working correctly, but this PR does not contain the final link?

**Comment by gtmills** [comment]
> Taking a same example  ./static/redfish/v1/JsonSchemas/AllowDeny/AllowDeny.json, it looks like the link is still pointing to ../../../../../redfish-core/schema/dmtf/json-schema/AllowDeny.v1_0_2.json. 

Had to rerun my script downstream. Straight cherry-picking did not work since we include all the schemas downstream.

**Review by baemyung — APPROVED** [review]
It seems good.

**Pull request merged**
