### PR TITLE
Improve base64Decode bounds checking

### PR DESCRIPTION
**Pull request by joseph-reynolds**
This is a backport of commit 5beaf840 into the OP940 branch.
The unit test code is omitted from the backport.
Tested: Yes, basic auth uses Base64.

Original commit message:

Index the decode array with an unsigned char rather than a signed int
(which could accees outside the bounds of decodingData, leading to
undefined behavior).
Add unit tests for basic decoding functionality.
Remove duplicate unused base64 functions.

Tested: ran webtest and observed that previously failing
Base64DecodeNonAscii now passes. Also tested basic auth:
  $ curl -vku root:0penBmc https://<ip>/redfish/v1/Managers/bmc
  ...
  < HTTP/1.1 200 OK
  ...

Change-Id: I9f9e32650b1796f9fc0b2b25d482dffa35fac72d
Signed-off-by: Jonathan Doman <jonathan.doman@intel.com>
Signed-off-by: Joseph Reynolds <joseph-reynolds@charter.net>

Conflicts:
	CMakeLists.txt
	src/base64.cpp

### CODE REVIEW

**Review by sunharis — CHANGES_REQUESTED** [review]
Please update the commit message to remove:

Conflicts:
CMakeLists.txt
src/base64.cpp

**Comment by joseph-reynolds** [comment]
I've updated the commit message to (1) remove the conflicts, and (2) remove the incorrect statement about omitting the test cases.  The test cases are included.

**Comment by gtmills** [comment]
Can you also remove in the PR? 
```
Conflicts:
CMakeLists.txt
src/base64.cpp
```

**Review by gtmills — APPROVED** [review]

**Comment by gtmills** [comment]
> Can you also remove in the PR message ?

I cleaned up

**Pull request merged**
